server:
 port: 8081
spring:
 h2:
  console:
   enabled: true
 datasource:
   driver-class-name: org.hsqldb.jdbcDriver
   password: 
   url: jdbc:hsqldb:hsql://localhost/
   username: SA
 jpa:
  properties:
   hibernate:
    dialect: org.hibernate.dialect.HSQLDialect
  hibernate:
   ddl-auto: create
  show-sql: true
  